on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

name: Build

jobs:
  build-lualatex:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
        name: build with latexmk (lualatex)
      - uses: actions/upload-artifact@v2
        with:
          path: main.pdf
          name: main-lualatex.pdf
        name: upload build artifacts
  build-xelatex:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
        name: build with latexmk (xelatex)
      - uses: actions/upload-artifact@v2
        with:
          path: main.pdf
          name: main-xelatex.pdf
        name: upload build artifacts
