on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

name: Build

jobs:
  build-xelatex:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: .github/ci/build_test_variants.sh -halt-on-error -time -quiet -xelatex
        name: build test variants with XeLaTeX
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: .github/ci/gen_cover.sh -halt-on-error -time -quiet -xelatex
        name: build cover with XeLaTeX
      - run: cat build/build-*.log
        name: display build log
        if: ${{ failure() || success() }}
      - uses: actions/upload-artifact@v2
        with:
          path: |
            build/build-*.pdf
            build/cover.pdf
          name: build-xelatex
        name: upload build artifacts
  build-lualatex:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: .github/ci/build_test_variants.sh -halt-on-error -time -quiet -lualatex
        name: build test variants with LuaLaTeX
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: .github/ci/gen_cover.sh -halt-on-error -time -quiet -lualatex
        name: build cover with LuaLaTeX
      - run: cat build/*.log
        name: display build log
        if: ${{ failure() || success() }}
      - uses: actions/upload-artifact@v2
        with:
          path: |
            build/build-*.pdf
            build/cover.pdf
          name: build-lualatex
        name: upload build artifacts
  build-package:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            export diffexe="diff -U 3"
            apk add zip diffutils
            .github/ci/build_package.sh
        name: build package with l3build
      - name: check if generated files are of latest version
        run: |
          git diff --exit-code
      - uses: actions/upload-artifact@v2
        with:
          path: |
            src/build/distrib/tds/doc
            src/build/distrib/tds/source
            src/build/distrib/tds/tex
          name: sjtubeamer.tds
        name: upload build artifacts
  check-format:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add diffutils git
            git ls-files | grep .tex$ | xargs -n1 latexindent -l latexindent.yaml -w > /dev/null
            git ls-files | grep .dtx$ | xargs -n1 latexindent -l latexindent.yaml -w > /dev/null
      - name: check if generated files are of latest version
        run: |
          git diff --exit-code
