on:
  push:
    branches:
    - release
    tags:
    - "v*"

name: Release

jobs:
  release-xelatex:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            .github/ci/build_package.sh
            .github/ci/build_all_variants.sh -halt-on-error -time -quiet -xelatex
        name: build with XeLaTeX
      - run: cat build-*.log
        name: display build log
        if: ${{ failure() || success() }}
      - uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          prerelease: true
      - name: add build-maxplus-blue
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/build-maxplus-blue.pdf
          asset_name: doc-theme-maxplus-blue.pdf
          asset_content_type: application/pdf
      - name: add build-maxplus-red
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/build-maxplus-red.pdf
          asset_name: doc-theme-maxplus-red.pdf
          asset_content_type: application/pdf
      - name: add build-max-red
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/build-max-red.pdf
          asset_name: doc-theme-max-red.pdf
          asset_content_type: application/pdf
      - name: add build-min-red
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/build-min-red.pdf
          asset_name: doc-theme-min-red.pdf
          asset_content_type: application/pdf
      - name: add covers
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/cover.pdf
          asset_name: sample-all-covers.pdf
          asset_content_type: application/pdf
      - name: add ctan zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/sjtubeamer-ctan.zip
          asset_name: sjtubeamer-ctan.zip
          asset_content_type: application/zip
      - name: add devguide
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/build/distrib/ctan/sjtubeamer/sjtubeamerdevguide.pdf
          asset_name: sjtubeamer-dev-guide.pdf
          asset_content_type: application/pdf
      - name: add intro
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/build/distrib/ctan/sjtubeamer/sjtubeamer.pdf
          asset_name: sjtubeamer-intro.pdf
          asset_content_type: application/pdf
